### ISSUE TITLE
ICE Connection [POSSIBLE_BUG]

### ISSUE THREAD

**Issue by Mattchewone** [twilio/twilio-client.js#14] opened 2019-06-13 22:05 UTC
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

https://codepen.io/mattchewone-the-looper/pen/OeygKW

![Screenshot 2019-06-13 at 23 00 16](https://user-images.githubusercontent.com/4574152/59470286-27920980-8e2f-11e9-9d7a-e0105ebd620a.png)

By just having an instance of `Device` a Peer Connection is created as you can see from the above screenshot and demo with codepen.

**Expected behavior:**

PeerConnection shouldn't be created until `Device.setup(<token>)` is called, or `new Device(<token>)` with a token is provided.

**Actual behavior:**

When creating a new instance, a peer connection is created, then when `Device.setup('token')` is called later, another peer connection is also created.

**Comment by makarandp0** [comment] 2019-06-13 22:30
Thank you for reporting this issue @Mattchewone. I was able to reproduce it, and found that its caused by a temporary peerConnection created by twilio-video.  Twilio SDK creates this temporary PeerConnection as soon as it's included to check the sdpFormat supported by chrome. This value is cached for rest of the session use.  

this leads to the PeerConnection creation 
https://github.com/twilio/twilio-webrtc.js/blob/master/lib/util/sdp.js#L21

and this is where its invoke from.
https://github.com/twilio/twilio-video.js/blob/master/lib/signaling/v2/peerconnection.js#L38


This should not cause any side effects, but I agree that it can be avoided. I will file an internal bug to track this issue.

**Comment by charliesantos** [comment] 2019-06-13 22:38
Hi @Mattchewone,

Thank you for reporting this. We will take a look and get back to you when we have more information.

Thanks,

Charlie Santos
JSDK Team

**Comment by ryan-rowland** [comment] 2019-06-14 17:14
Hi @Mattchewone, it looks like you're noticing the temporary RTCPeerConnection we use on `Device.setup()` to determine whether `plan-b` or `unified-plan` is default on the browser. We use this information to guide which logic fork to follow for adding and removing tracks because the methods used for each of those two SDP semantics are different.

**Comment by ryan-rowland** [comment] 2019-06-14 17:44
Well, I say "temporary" but I see we're not attempting to close it. So the bad behavior here is that we're not closing it when it's done! Thanks for pointing this out.

**Comment by Mattchewone** [comment] 2019-06-14 17:49
👍 

I see that with the `Device.setup(<token>, { ... options })` you can add `iceServers` here when calling `Device.setup` which I do but I do this later within the app. 

Is there a way to postpone making the "initialization"? We don't always need to make calls, wouldn't it be better to do this during calling `.setup()`?

We are running some automated tests on our WebRTC app which test ICE by using firewalls, and we are getting failures on this "initialization" request as it doesn't have our own `iceServer` configurations.

**Comment by ryan-rowland** [comment] 2019-06-21 17:33
Slated for next release.

**Closed by ryan-rowland** 2019-06-21 17:33 UTC
Labels: bug, verified
