### ISSUE TITLE
[BUG] mic gets unmuted

### ISSUE THREAD

**Issue by mesqueeb** [twilio/twilio-client.js#206] opened 2020-07-31 00:49 UTC
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

This is the listener:
```ts
this.connection.on("mute", (isMutedState: boolean) => {
                console.log(`twilio event: isMutedState → `, isMutedState)
                this.isMuted = isMutedState
            })
```

This is what I use to mute:

```ts
this.connection.mute(true) // local state updated by event handler
```

A connection is something like:
```ts
this.connection = this.device.connect(twilioConferenceParamsCustom as any)
```

**Actual behavior:**

Everything works most of the time. But very rarely when a user mutes their microphone, Twilio reverts the muted state change about 200ms after the mic is muted.

Eg. my console log (as per the event listener above says:)
```
twilio event: isMutedState → true
twilio event: isMutedState → false
```
directly after each other.

**Expected behavior:**

This should never happen.

**Software versions:**

 - [x] Browser(s): Google chrome latest v
 - [x] Operating System: macOS
 - [x] twilio.js: yes
 - [x] Third-party libraries (e.g., Angular, React, etc.): yes, Vue

**Comment by charliesantos** [comment] 2020-07-31 16:14
Hi @mesqueeb , unfortunately I'm not able to reproduce. Do you have a 100% reproduction steps?

**Comment by mesqueeb** [comment] 2020-08-01 01:54
@charliesantos Sadly I'm not able to reproduce it 100% myself... It just happens sporadically.

We have logged this as an open issue inside our company as well and I have attached the link to this github thread.

Once we're able to create a reproduction that 100% causes the issue, I will come back here and report.

**Comment by charliesantos** [comment] 2020-08-03 16:29
Sounds good @mesqueeb . We also have not received any reports related to this issue. I'll close this for now since we cannot reproduce. But please reopen once you get a reproduction steps. And feel free to send follow up questions.

**Closed by charliesantos** 2020-08-03 16:29 UTC
Labels: answered, bug, not reproducible
