### ISSUE TITLE
[BUG] Error code 9221 expired token

### ISSUE THREAD

**Issue by stochris** [twilio/twilio-client.js#73] opened 2019-09-18 14:19 UTC
- [x] I have verified that the issue occurs with the latest twilio.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-client.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-client.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/TwilioDevEd/client-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**The issue:**

Sometimes, network calls to `https://eventgw.twilio.com/v4/EndpointEvents` ( automatically called when a twilio call is ended, no way to prevent it) returns a `403` with the following exception being caught in sentry
```
{"code":9221,"message":"Expired token"}
```

I am openng this issue as the code `9221` is not documented anywhere, and I'm not sure where to even catch the problem.

I suspect this is caused by the token expiring while the call is open, then at the end, not having the new token prevents a successful network call.

However, what confuses me is the error code, which doesn't seem to be documented anywhere

**Software versions:**

 - [x] Browser(s):Chrome
 - [x] Operating System: Windows, macOS
 - [x] twilio.js: 1.9.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): AngularJS ( angular 1 )

**Comment by maxannear** [comment] 2019-10-10 20:03
> I suspect this is caused by the token expiring while the call is open, then at the end, not having the new token prevents a successful network call.

We also have this issue and I'm confident this isn't the cause. In prod I've correlated this error showing in sentry with when they refresh the token and often they have a new token. 

I've also just had this happen locally in our electron app. I had the app open when I closed my laptop yesterday. This morning it got a new capability token and I can make and receive calls with that token but I was getting 403 to the EndpointMetrics and EndpointEvents. Interestingly when it got another capability token (second time this morning) it correctly updated all the insights requests are working correctly.

My guess is somehow the new token isn't alway correctly set in the code that manages insights?

**Comment by youssseeef** [comment] 2019-10-18 22:51
I have this also happen on a web app using Twilio, I'm using version 1.7.0 of the sdk. I detected the issue via Sentry and it looks like I'm also getting 403s on EndpointEvents like @maxannear . I'm not sure if there's a better place to report this since it might be related to something related to the backend on Twilio's side but it looks common since it's generating a lot of events to Sentry.

**Comment by ryan-rowland** [comment] 2019-10-23 18:19
The code is internal to Insights, and should be updated to match the publicly defined error codes. This issue is known internally -- we currently have an array of betterments in the backlog for improving and making error codes more consistent between products / services.

You won't currently be able to catch this error because the Insights reporting is happening in the background, and we're not currently firing an error event for this. I think a short-term betterment here is to fire an event for this, so I'll add a ticket to the backlog for investigating this. The one potential issue I see here is how some customers may consume the error event. Adding a new event could have some unintended consequences in existing applications, because now the `Connection#error` and/or `Device#error` events would not only indicate call/signaling errors but also Insights errors.

Long term, we'd like to actually authenticate once and keep a session open, rather than requiring the auth token for each request, in line with our pre-Insights recommendation of minting short-lived (<10sec) tokens as-needed to register a Device. This under discussion and exists on the roadmap at some point but I can't speak to the timeline.

For the time being, I'd highly suggest *not* relying on an error code to tell you when a token has a expired. Instead, set a timer to update the token, at an interval of the TTL of the token minus some reasonable overlap so that the Device is never using an expired token.

**Comment by stochris** [comment] 2019-10-30 17:06
Thanl you for the suggestion. It indeeds solves all the issues we've been facing, and is really simple :smiley: 
This issue initially appeared when sentry started reported http issues on the EndpointEvents api call. Would be awesome if in the future there's a way to catch errors there before they bubble up the event chain all the way to `window.onunhandledrejection`

**Comment by ryan-rowland** [comment] 2019-10-31 20:11
Yeah, I'm currently investigating ways to surface these errors in a useful way. I have a ticket in our internal backlog for that improvement now!

Thanks again for the report, I'm glad the suggestion helped! I'm going to close this ticket now for our tracking but everything discussed in this thread has been discussed internally and has appropriate tickets in our backlog.

**Closed by ryan-rowland** 2019-10-31 20:11 UTC
Labels: bug
